import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.primary,
            width: 2.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.only(
              topLeft: Radius.circular(0.h),
              topRight: Radius.circular(0.h),
              bottomLeft: Radius.circular(6.h),
              bottomRight: Radius.circular(6.h),
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.only(
              topLeft: Radius.circular(0.h),
              topRight: Radius.circular(0.h),
              bottomLeft: Radius.circular(6.h),
              bottomRight: Radius.circular(0.h),
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        headlineMedium: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: 26.fSize,
          fontFamily: 'Gemunu Libre',
          fontWeight: FontWeight.w400,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 22.fSize,
          fontFamily: 'Gemunu Libre',
          fontWeight: FontWeight.w400,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF8249B5),
    primaryContainer: Color(0XFFFBFBFB),
    secondary: Color(0XFFFBFBFB),
    secondaryContainer: Color(0XFF8249B5),
    tertiary: Color(0XFFFBFBFB),
    tertiaryContainer: Color(0XFF8249B5),

    // Background colors
    background: Color(0XFFFBFBFB),

    // Surface colors
    surface: Color(0XFFFBFBFB),
    surfaceTint: Color(0XFFFBFBFB),
    surfaceVariant: Color(0XFF8249B5),

    // Error colors
    error: Color(0XFFFBFBFB),
    errorContainer: Color(0XFF8249B5),
    onError: Color(0XB2323232),
    onErrorContainer: Color(0XFFFBFBFB),

    // On colors(text colors)
    onBackground: Color(0XB2323232),
    onInverseSurface: Color(0XB2323232),
    onPrimary: Color(0XFFFBFBFB),
    onPrimaryContainer: Color(0XB2323232),
    onSecondary: Color(0XB2323232),
    onSecondaryContainer: Color(0XFFFBFBFB),
    onTertiary: Color(0XB2323232),
    onTertiaryContainer: Color(0XFFFBFBFB),

    // Other colors
    outline: Color(0XFFFBFBFB),
    outlineVariant: Color(0XFFFBFBFB),
    scrim: Color(0XFFFBFBFB),
    shadow: Color(0XFFFBFBFB),

    // Inverse colors
    inversePrimary: Color(0XFFFBFBFB),
    inverseSurface: Color(0XFFFBFBFB),

    // Pending colors
    onSurface: Color(0XB2323232),
    onSurfaceVariant: Color(0XFFFBFBFB),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // BlueGray
  Color get blueGray400 => Color(0XFF808194);
  Color get blueGray40001 => Color(0XFF888888);

  // DeepPurple
  Color get deepPurpleA700 => Color(0XFF5D13E7);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
